const BankAccount = require('./bank')

let account1 = new BankAccount("checking", 4)
let account2 = new BankAccount("savings", 100)

console.log('Account 1')
console.log(`Opening balance: $${account1.balance}`)
console.log(`Type: ${account1.type}`)
account1.deposit(150)
account1.withdraw(30)
account1.withdraw(10)
account1.showBalance()
account1.transactionHistory()
console.log("")

console.log('Account 2')
console.log(`Opening balance: $${account2.balance}`)
console.log(`Type: ${account2.type}`)
account2.withdraw(25)
account2.deposit(5)
account2.deposit(100)
account2.showBalance()
account2.transactionHistory()
console.log("")

